name: CheckPing
version: 1.0
author: Tarkod
main: fr.tarkod.checkping.CheckPingMain
commands:
  ping:
    aliases: [p, cp, cping, checkp]
    description: To check your or their ping.
  myping:
    aliases: [mp, mping, myp]
    description: To check your ping.
  cprl: